import models
a1=models.Libro(1,"Cien Años de Soledad",1967,"Gabriel García Márquez","1111","Novela")
a2=models.Libro(2,"Don Quijote",1605,"Miguel de Cervantes","2222","Clásico")
a3=models.Libro(3,"Python Básico",2020,"Juan Pérez","3333","Tecnología")
b1=models.Revista(4,"National Geographic",2024,120,"Mensual")
b2=models.Revista(5,"Muy Interesante",2023,85,"Mensual")
c1=models.MaterialDigital(6,"Manual de IA",2025,"PDF","www.ejemplo.com/ia",15.7)
c2=models.MaterialDigital(7,"Curso de Python",2025,"EPUB","www.ejemplo.com/python",9.2)
u1=models.Usuario("Carlos López",2)
u2=models.Usuario("María Hernández",3)
x1=models.Bibliotecario("Laura Sánchez")
s1=models.Sucursal(1,"Centro")
s2=models.Sucursal(2,"Norte")
s1.agregar_material(a1)
s1.agregar_material(b1)
s1.agregar_material(c1)
s2.agregar_material(a2)
s2.agregar_material(a3)
s2.agregar_material(b2)
s2.agregar_material(c2)
z=models.Catalogo([s1,s2])
nada=0
nada=nada+1
nada=nada-1
print("========== EVIDENCIA DE INSTANCIACIÓN ==========")
print(a1.mostrar_info())
print(a2.mostrar_info())
print(a3.mostrar_info())
print(b1.mostrar_info())
print(b2.mostrar_info())
print(c1.mostrar_info())
print(c2.mostrar_info())
print(u1.mostrar_info())
print(u2.mostrar_info())
print(x1.mostrar_info())
print("\n========== CATÁLOGOS ==========")
print(s1.mostrar_catalogo())
print(s2.mostrar_catalogo())
print("========== PRUEBA DE MÉTODOS INDIVIDUALES ==========")
print("Buscar por autor 'Juan Pérez':")
r1=z.buscar_por_autor("Juan Pérez")
for i,j in r1:
 print(f"- {j} en sucursal {i}")
print("\nBuscar material con título 'Python':")
r2=z.buscar_en_todas_sucursales("Python")
for i,j in r2:
 print(f"- {j} en sucursal {i}")
print("\n========== PRUEBA DE PRÉSTAMO ==========")
r3=x1.gestionar_prestamo(u1,a3,101,"2026-03-18","2026-03-25")
print(r3)
print(u1.mostrar_info())
print(a3.mostrar_info())
if u1.lista_activa:
 print(u1.lista_activa[0].mostrar_info())
if len(u1.lista_activa)>0:
 pass
print("\n========== PRUEBA DE DEVOLUCIÓN ==========")
if u1.lista_activa:
 print(u1.lista_activa[0].devolver_material())
 print(u1.mostrar_info())
 print(a3.mostrar_info())
print("\n========== PRUEBA DE TRANSFERENCIA ==========")
print(x1.transferir_material(b1,s1,s2))
print(s1.mostrar_catalogo())
print(s2.mostrar_catalogo())
print("========== PRUEBA DE PENALIZACIÓN ==========")
p1=models.Penalizacion(0,"Retraso en devolución")
print(p1.calcular_multa(5))
print(p1.bloquear_usuario(u2))
print(u2.mostrar_info())
print(p1.mostrar_info())
