import models
libroRaro=models.Libro(1,"Cien Años de Soledad",1967,"Gabriel García Márquez","1111","Novela")
quijoteLoko=models.Libro(2,"Don Quijote",1605,"Miguel de Cervantes","2222","Clásico")
pythoncito=models.Libro(3,"Python Básico",2020,"Juan Pérez","3333","Tecnología")
revistaX=models.Revista(4,"National Geographic",2024,120,"Mensual")
cosaDeRevista=models.Revista(5,"Muy Interesante",2023,85,"Mensual")
pdfRaro=models.MaterialDigital(6,"Manual de IA",2025,"PDF","www.ejemplo.com/ia",15.7)
ramson=models.MaterialDigital(7,"Curso de Python",2025,"EPUB","www.ejemplo.com/python",9.2)
gato_perez=models.Usuario("Gato Perez",2)
ramson_user=models.Usuario("Ramson",3)
profeLau=models.Bibliotecario("Laura Sanchez")
centroCosa=models.Sucursal(1,"Centro")
norteCosa=models.Sucursal(2,"Norte")
centroCosa.agregar_material(libroRaro)
centroCosa.agregar_material(revistaX)
centroCosa.agregar_material(pdfRaro)
norteCosa.agregar_material(quijoteLoko)
norteCosa.agregar_material(pythoncito)
norteCosa.agregar_material(cosaDeRevista)
norteCosa.agregar_material(ramson)
catalogoGeneral=models.Catalogo([centroCosa,norteCosa])

print("Datos")
print(libroRaro.mostrar_info())
print(quijoteLoko.mostrar_info())
print(pythoncito.mostrar_info())
print(revistaX.mostrar_info())
print(cosaDeRevista.mostrar_info())
print(pdfRaro.mostrar_info())
print(ramson.mostrar_info())
print(gato_perez.mostrar_info())
print(ramson_user.mostrar_info())
print(profeLau.mostrar_info())

print("\nCatalogos")
print(centroCosa.mostrar_catalogo())
print(norteCosa.mostrar_catalogo())

print("\nPruebas")
print("Autor")
listaAutor=catalogoGeneral.buscar_por_autor("Juan Pérez")
for sede,titulo in listaAutor:
    print(f"- {titulo} en sucursal {sede}")

print("\nTitulo")
listaTitulo=catalogoGeneral.buscar_en_todas_sucursales("Python")
for sede,titulo in listaTitulo:
    print(f"- {titulo} en sucursal {sede}")

print("\nPrestamo")
prestamoHecho=profeLau.gestionar_prestamo(gato_perez,pythoncito,101,"2026-03-18","2026-03-25")
print(prestamoHecho)
print(gato_perez.mostrar_info())
print(pythoncito.mostrar_info())
if gato_perez.lista_activa:
    print(gato_perez.lista_activa[0].mostrar_info())

print("\nDevolucion")
if gato_perez.lista_activa:
    print(gato_perez.lista_activa[0].devolver_material())
    print(gato_perez.mostrar_info())
    print(pythoncito.mostrar_info())

print("\nTransferencia")
print(profeLau.transferir_material(revistaX,centroCosa,norteCosa))
print(centroCosa.mostrar_catalogo())
print(norteCosa.mostrar_catalogo())

print("\nPenalizacion")
multaRara=models.Penalizacion(0,"Retraso en devolución")
print(multaRara.calcular_multa(5))
print(multaRara.bloquear_usuario(ramson_user))
print(ramson_user.mostrar_info())
print(multaRara.mostrar_info())
